//! P4-STATEFUL criterion 14b's pre-gate-2 baseline: the enumerator's
//! `format!("{verdict}")` on two named fixtures, captured on the working tree
//! `bd793be` + Parts 1–2 before the lead's first gate-2 edit to `report.rs`.
//!
//! Both runs use `ConfBuilder::new().config(Config::builder().with_seed(7).build())
//! .visible_threads(..)` and nothing else, through `conformance::run`. The
//! constants were generated by running the two renders once and pasting the
//! output; they are not to be edited to match a later render. The gate-3 test
//! asserts byte equality against them.

/// `enumerator_tests::naive_d(2, 0, true, None)` (Impl) against
/// `naive_d(2, 1, true, None)` (Spec), `Tvis = naive_visible(2)`: `Reported`.
/// 2628 bytes.
pub(super) const ENUMERATOR_REPORTED_BASELINE: &str = concat!(
    "conformance: run seed 7 (reproduce with the same `Config` plus `.with_seed(7)`)\n",
    "conformance: 1 candidate violation(s).\n",
    "What this report establishes (Lemma gate, modulo the draft's own lemmas): no complete specification graph covers any event-extension of the reported graph.\n",
    "What this report does not establish, which is a different claim about a different thing: that the report list is complete.\n",
    "This list is not a complete set of violations: a lost backward revisit can suppress other reports, and how often is unmeasured (backlog A1).\n",
    "\"Candidate\" has two named sources: (i) single-cover is sufficient but not necessary for trace inclusion, so a union of specification graphs may still cover these traces; (ii) the lemmas this rests on carry the open A4 transport gap.\n",
    "Only silence is a verdict: a run that produced no report, hit no search budget and reached the end of its state space is the certificate, and nothing else is.\n",
    "\n",
    "#0\n",
    "  candidate violation: no specification graph covers the implementation graph below\n",
    "  raised at: the fresh-send gate — the tail of `handle_send`, after the send was installed and its revisits computed\n",
    "  certifies (GrowingExhaustion): no partial graph of the specification matches the reported graph, so every completion of every extension of it is uncovered (cor:absence)\n",
    "  implementation graph size: 12 events\n",
    "  inner-search diagnostics (recomputed after the run, so they did not influence it):\n",
    "    furthest-following attempt, by visible-thread observation count: [a: 0, c: 0, b1: 0, b2: 0]\n",
    "    first failing obligation: (M1) observation mismatch on `c` at position 0: the specification has nothing here (this attempt's row ends, though another attempt of the specification observed send 1 at this position), the implementation has send 0\n",
    "  implementation graph:\n",
    "    Printing exec graph\n",
    "    thread \"main\"[tid=t0]:\n",
    "    \t(t0, 0): BEGIN\n",
    "    \t(t0, 1): UNIQUE [NoOrder]\n",
    "    \t(t0, 2): UNIQUE [NoOrder]\n",
    "    \t(t0, 3): TCREATE(t1:\"c\")\n",
    "    \t(t0, 4): TCREATE(t2:\"b1\")\n",
    "    \t(t0, 5): TCREATE(t3:\"b2\")\n",
    "    \t(t0, 6): TCREATE(t4:\"a\")\n",
    "    thread \"c\"[tid=t1]:\n",
    "    \t(t1, 0): BEGIN\n",
    "    \t(t1, 1): SEND(TSome(Loc(Event { thread: ThreadId { opaque_id: 0 }, index: 1 })), Val { val: 0, type_name: \"i32\" })\n",
    "    thread \"b1\"[tid=t2]:\n",
    "    \t(t2, 0): BEGIN\n",
    "    thread \"b2\"[tid=t3]:\n",
    "    \t(t3, 0): BEGIN\n",
    "    thread \"a\"[tid=t4]:\n",
    "    \t(t4, 0): BEGIN\n",
    "  serialized replay information (7404 bytes of JSON) is attached to this report; see `ConfReport::replay_snapshot`\n",
    "\n",
    "triage is off (the default). `ConfBuilder::triage(true)` completes each reported graph into a concrete trace, at the cost of one extra engine run per report.\n",
);

/// `selector_tests::restart(true)` against itself, `Tvis = ["a", "c"]`:
/// `Conforms`. 542 bytes.
pub(super) const ENUMERATOR_CONFORMS_BASELINE: &str = concat!(
    "conformance: run seed 7 (reproduce with the same `Config` plus `.with_seed(7)`)\n",
    "conformance: silence. No candidate violation, no exhausted search budget, and the outer loop reached the end of its state space.\n",
    "Only silence is a verdict: a run that produced no report, hit no search budget and reached the end of its state space is the certificate, and nothing else is.\n",
    "This run therefore certifies visible-trace refinement of the specification by the implementation, resting on:\n",
    "  - the draft's own lemmas, including the open A4 transport gap\n",
);
